name = "stock-journal"
compatibility_date = "2026-06-11"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "stock-journal"
database_id = "09509c94-189b-4589-9941-f2da6bb99cc3"
